apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logcollectors.local.com
spec:
  group: local.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                podSelector:
                  type: string
                bucket:
                  type: string
                minioEndpoint:
                  type: string
                accessKey:
                  type: string
                secretKey:
                  type: string
                debug:
                  type: string
                rewrite:
                  type: string
                push_interval:
                  type: string
  scope: Namespaced
  names:
    plural: logcollectors
    singular: logcollector
    kind: LogCollector
    shortNames:
      - lc