apiVersion: v1
kind: ServiceAccount
metadata:
  name: logcollector-operator
  namespace: logcollector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logcollector-operator-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["local.com"]
  resources: ["logcollectors"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logcollector-operator-binding
subjects:
- kind: ServiceAccount
  name: logcollector-operator
  namespace: logcollector
roleRef:
  kind: ClusterRole
  name: logcollector-operator-role
  apiGroup: rbac.authorization.k8s.io